name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Release
      env:
        DATABASE_URL: "sqlite://db/db.db"
      run: |
        cargo build --release
    - name: Clippy
      env:
        DATABASE_URL: "sqlite://db/db.db"
      run: |
        cargo clippy
